name: build-prerelease

on:
  push:
    branches:
      - prerelease

jobs:
  run:
    name: Pre-Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up V version latest
        uses: nocturlab/setup-vlang-action@v1
        with:
          v-version: latest
        id: v
      - name: Build repository app
        run: v -prod laravel_permissions.v -o laravel_permissions -os linux
      - name: Release binary to latest tag
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Pre-Release Build for Linux"
          files: |
            laravel_permissions
