name: build-tagged

on:
  push:
    tags:
      - "v*"

jobs:
  run:
    name: Tagged Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up V version latest
        uses: nocturlab/setup-vlang-action@v1
        with:
          v-version: latest
        id: v
      - name: Build repository app
        run: v -prod ngc.v -o ngc -os linux
      - name: Release binary to latest tag
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "Production Build for Linux"
          files: |
            ngc
